service: product-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  iam:
    role: 
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:GetItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Scan"
            - "dynamodb:Query"
            - "dynamodb:PutItem"
          Resource: "*"
  environment:
    PRODUCTS_TABLE: products
    STOCKS_TABLE: stocks
    
plugins:
  - serverless-webpack
  - serverless-jest-plugin

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    dbTableName: "products"

functions:
  getProductsList:
    handler: handlers/getProductsList.getProductsList
    events:
      - http:
          path: /products
          method: get  	
  getProductsById:
    handler: handlers/getProductsById.getProductsById
    events:
      - http:
          path: /products/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
  createProduct:
    handler: handlers/createProduct.createProduct
    events:
      - http:
          path: /products
          method: post